WebNavigationTestProject/Areas/Area51/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebNavigationTestProject.Areas.Area51.Controllers
{
    [Area("Area51")]
    [Authorize(Policy = "EmployeesOnly")]
    public class HomeController : Controller
    {
        [Authorize(Policy = "Over21")]
        public IActionResult Index()
        {
            ViewData["Message"] = "Your area description page.";

            return View();
        }
    }
}

WebNavigationTestProject/Areas/Area51/Controllers/RoswellController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebNavigationTestProject.Areas.Area51.Controllers
{
    [Area("Area51")]
    [Authorize(Policy = "EmployeesOnly")]
    public class RoswellController : Controller
    {
        public RoswellController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Policy = "Over21")]
        public IActionResult Aliens()
        {
            return View();
        }

        [Authorize(Policy = "Over21")]
        [HttpPost]
        public IActionResult Aliens(int id)
        {
            return View();
        }
        public IActionResult MenInBlack()
        {
            return View();
        }

    }
}

WebNavigationTestProject/Controllers/FakeAccountController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;

namespace WebNavigationTestProject.Controllers
{
    [Authorize]
    public class FakeAccountController : Controller
    {
        public FakeAccountController()
        {

        }

        // GET: /Account/index
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewData["Title"] = "Login";
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string userName = null)
        {
            //fake login with roles to demonstrate role based menu filtering
            AuthenticationProperties authProperties = new AuthenticationProperties();
            ClaimsPrincipal user;
            switch(userName)
            {
                case "Administrator":
                    user = GetAdminClaimsPrincipal();
                    break;
                case "EmployeeOver21":
                    user = GetEmployeeClaimsPrincipal(33);
                    break;
                case "EmployeeUnder21":
                    user = GetEmployeeClaimsPrincipal(19);
                    break;
                case "Member":
                default:
                    user = GetMemberClaimsPrincipal();
                    break;
            }
            await HttpContext.SignInAsync("application", user, authProperties);

            return RedirectToAction(nameof(HomeController.Index), "Home");


            //return View("Index");
        }

        private ClaimsPrincipal GetAdminClaimsPrincipal()
        {
            var identity = new ClaimsIdentity("application");
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, "1"));
            identity.AddClaim(new Claim(ClaimTypes.Name, "Administrator"));
            identity.AddClaim(new Claim(ClaimTypes.Role, "Admins"));


            return new ClaimsPrincipal(identity);
        }

        private ClaimsPrincipal GetMemberClaimsPrincipal()
        {
            var identity = new ClaimsIdentity("application");
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, "1"));
            identity.AddClaim(new Claim(ClaimTypes.Name, "Member"));
            identity.AddClaim(new Claim(ClaimTypes.Role, "Members"));


            return new ClaimsPrincipal(identity);
        }

        private ClaimsPrincipal GetEmployeeClaimsPrincipal(int age)
        {
            var identity = new ClaimsIdentity("application");
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, "1"));
            identity.AddClaim(new Claim(ClaimTypes.Name, age + "yoEmployee"));
            identity.AddClaim(new Claim(ClaimTypes.Role, "Members"));
            identity.AddClaim(new Claim("EmployeeId", age.ToString()));
            identity.AddClaim(new Claim(ClaimTypes.DateOfBirth, (DateTime.Today.Year - age) + "-01-01"));
            return new ClaimsPrincipal(identity);
        }

        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            //await _signInManager.SignOutAsync();
            await HttpContext.SignOutAsync("application");

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

    }
}

WebNavigationTestProject/Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

namespace WebNavigationTestProject.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult AboutMe()
        {
            ViewData["Message"] = "about me page.";

            return View("About");
        }

        public IActionResult AboutCompany()
        {
            ViewData["Message"] = "about company page.";

            return View("About");
        }

        public IActionResult AboutProject()
        {
            ViewData["Message"] = "about project page.";

            return View("About");
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult HideAuth()
        {
            ViewData["Message"] = "Your contact page.";

            return View("Contact");
        }
        [Authorize(Roles = "Admins")]
        public IActionResult HideAnon()
        {
            ViewData["Message"] = "Your contact page.";

            return View("Contact");
        }

        public IActionResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }

        [Authorize(Roles = "Admins")]
        public IActionResult Administration()
        {
            ViewData["Message"] = "Administrators only.";
            
            return View();
        }

        [Authorize(Roles = "Admins,Members")]
        public IActionResult Members()
        {
            ViewData["Message"] = "Members only.";

            return View();
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        [HttpPost]
        public IActionResult ClearLanguageCookie(string culture, string returnUrl)
        {
            Response.Cookies.Delete(
                CookieRequestCultureProvider.DefaultCookieName
            );

            return LocalRedirect(returnUrl);
        }
    }
}

WebNavigationTestProject/Areas/Area51/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

This is the area home index view

WebNavigationTestProject/Areas/Area51/Views/Roswell/Aliens.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

This is the aliens view for Roswell controller in area51

WebNavigationTestProject/Areas/Area51/Views/Roswell/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

This is the index view for Roswell controller in area51

WebNavigationTestProject/Areas/Area51/Views/Roswell/MenInBlack.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

This is the MenInBlack view for Roswell controller in area51

WebNavigationTestProject/Views/FakeAccount/Index.cshtml
@{
    
}

<h2>@ViewData["Title"].</h2>

<form asp-controller="FakeAccount" asp-action="Login" method="post" class="form-horizontal" role="form">
    
    <div class="form-group">
        <label class="col-md-2 control-label">Select User </label>
        <div class="col-md-10">
            <select id="userName" name="userName" class="form-control">
                <option value="Administrator">Administrator</option>
                <option value="Member">Member</option>
                <option value="EmployeeOver21">Employee Over 21 yo</option>
                <option value="EmployeeUnder21">Employee Under 21 yo</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Log in</button>
        </div>
    </div>
    
</form>

WebNavigationTestProject/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebNavigationTestProject/Views/Home/Administration.cshtml
@{
    ViewData["Title"] = "Administration";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

This view requires the administrators role.

WebNavigationTestProject/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebNavigationTestProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

WebNavigationTestProject/Views/Home/Members.cshtml
@{
    ViewData["Title"] = "Members Only";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

This view requires the Members role.

WebNavigationTestProject/Views/Shared/Components/Navigation/BootstrapBreadcrumbs.cshtml
@using cloudscribe.Web.Navigation
@using Microsoft.Extensions.Localization
@model NavigationViewModel
@inject  IStringLocalizer<WebNavigationTestProject.MenuResources> localizer
@if (Model.CurrentNode != null && Model.ParentChain.Count > 1)
{
    <ul class="breadcrumb">
    @foreach (var node in Model.ParentChain)
    {
        if (!Model.ShouldAllowView(node)) { continue; }
        if (node.EqualsNode(Model.CurrentNode))
        {
            if (Model.TailCrumbs != null)
            {
                <li><a href="@Url.Content(Model.AdjustUrl(node))">@localizer[Model.AdjustText(node)]</a><span class="divider"></span></li>
            }
            else
            {
                <li class="active">@localizer[Model.AdjustText(node)]</li>
            }
        }
        else
        {
            <li><a href="@Url.Content(Model.AdjustUrl(node))">@localizer[Model.AdjustText(node)]</a><span class="divider"></span></li>
        }
    }
    @if (Model.TailCrumbs != null)
    {
        foreach (var n in Model.TailCrumbs)
        {
            <li class="active">@localizer[n.Text]</li>
        }
    }
    </ul>
}

WebNavigationTestProject/Views/Shared/Components/Navigation/BootstrapTopNavWithDropdowns.cshtml
@using cloudscribe.Web.Navigation
@using Microsoft.Extensions.Localization
@using System.Text
@model NavigationViewModel
@inject  IStringLocalizer<WebNavigationTestProject.MenuResources> localizer
@addTagHelper *, cloudscribe.Web.Navigation
@if (Model.HasVisibleChildren(Model.RootNode))
{
    <ul class="nav navbar-nav" role="menubar">
        <li role="presentation" cwn-data-attributes="@Model.RootNode.Value.DataAttributes" class='@Model.GetClass(Model.RootNode.Value)'><a  href="@Url.Content(Model.AdjustUrl(Model.RootNode))">@Html.Raw(Model.GetIcon(Model.RootNode.Value))@localizer[Model.AdjustText(Model.RootNode)]</a></li>

        @foreach (var node in Model.RootNode.Children)
        {
            if (!Model.ShouldAllowView(node)) { continue; }
            if (!Model.HasVisibleChildren(node))
            {
                <li role="presentation" class='@Model.GetClass(node.Value)' cwn-data-attributes="@node.Value.DataAttributes"><a href="@Url.Content(Model.AdjustUrl(node))">@Html.Raw(Model.GetIcon(node.Value))@localizer[Model.AdjustText(node)]</a></li>
            }
            else
            {

                <li role="presentation" class='@Model.GetClass(node.Value, "dropdown")' cwn-data-attributes="@node.Value.DataAttributes">  
                    <a href="@Url.Content(Model.AdjustUrl(node))">@Html.Raw(Model.GetIcon(node.Value))@localizer[Model.AdjustText(node)] <span class="caret"></span></a>
                    @Model.UpdateTempNode(node)@Html.Partial("NavigationNodeChildDropdownPartial", Model)
                </li>
            }
        }
    </ul>
}

WebNavigationTestProject/Views/Shared/NavigationNodeChildDropdownPartial.cshtml
@using cloudscribe.Web.Navigation
@using Microsoft.Extensions.Localization
@model NavigationViewModel
@inject  IStringLocalizer<WebNavigationTestProject.MenuResources> localizer
@addTagHelper *, cloudscribe.Web.Navigation
@if ((Model.TempNode != null) && (Model.HasVisibleChildren(Model.TempNode)))
{
    <ul class="dropdown-menu" role="menu">
    @foreach (var childNode in Model.TempNode.Children)
    {
        if (!Model.ShouldAllowView(childNode)) { continue; }

        if (childNode.Value.Text == "Separator")
        {
            <li class="divider"></li>
                continue;
        }
        if (!Model.HasVisibleChildren(childNode))
        {
            <li role="presentation" class='@Model.GetClass(childNode.Value)' cwn-data-attributes="@childNode.Value.DataAttributes"><a href="@Url.Content(Model.AdjustUrl(childNode))">@Html.Raw(Model.GetIcon(childNode.Value))@localizer[Model.AdjustText(childNode)]</a></li>
        }
        else
        {
            <li role="presentation" class='@Model.GetClass(childNode.Value, "dropdown-submenu")' cwn-data-attributes="@childNode.Value.DataAttributes">
                <a href="@Url.Content(Model.AdjustUrl(childNode))">@Html.Raw(Model.GetIcon(childNode.Value))localizer[]@Model.AdjustText(childNode)] <span class="caret"></span></a>
                @Model.UpdateTempNode(childNode)@Html.Partial("NavigationNodeChildDropdownPartial", Model) @* recursion *@
            </li>
        }
    }
    </ul>
}

WebNavigationTestProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebNavigationTestProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/smartmenus/dist/addons/bootstrap/jquery.smartmenus.bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/smartmenus/dist/addons/bootstrap/jquery.smartmenus.bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" asp-area="" class="navbar-brand">WebNavigationTestProject</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Component.InvokeAsync("Navigation", new { viewName = "BootstrapTopNavWithDropdowns", filterName = NamedNavigationFilters.TopNav, startingNodeKey= "" }) 
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @await Component.InvokeAsync("Navigation", new { viewName = "BootstrapBreadcrumbs", filterName = NamedNavigationFilters.Breadcrumbs, startingNodeKey = "" })
        @RenderBody()
        <hr />
        @await Html.PartialAsync("_SelectLanguagePartial")
        <footer>
            <p>&copy; 2016 - WebNavigationTestProject</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/smartmenus/dist/jquery.smartmenus.js"></script>
        <script src="~/lib/smartmenus/dist/addons/bootstrap/jquery.smartmenus.bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/lib/smartmenus/dist/jquery.smartmenus.min.js"></script>
        <script src="~/lib/smartmenus/dist/addons/bootstrap/jquery.min.smartmenus.bootstrap.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        (function () {
            $("#selectLanguage select").change(function () {
                $(this).parent().submit();
            });
        }());
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>

WebNavigationTestProject/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal" role="form">
        @Localizer["Language:"] <select name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
    </form>
    <form id="selectLanguage" asp-controller="Home" asp-action="ClearLanguageCookie" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal" role="form">
        <button type="submit" class="btn btn-sm">@Localizer["Clear Language Cookie"]</button>
    </form>
</div>